### ISSUE TITLE
GTF output allowed to print positions in scientific notation

### ISSUE THREAD

**Issue by tzuni** [jpromeror/EventPointer#8] opened 2018-06-14 15:41 UTC
Hi,

Thanks for this great tool!

I just ran into this issue where having generated a CDF file from the UCSC annotation for an HTA_2.0 array, the paths.gtf that was generated contained lines like this:
```
chr3    EventPointer    transcript      112996945       1.13e+08        0       +       0       gene_id 91653_4; transcript_id "Ref3"_Retained_Intron_91653_4; type "Retained Intron"; color=#B0B0B0;
```
This is out of spec for GTF so other tools like `igvtools sort` choke on `1.13e+08`.

**Comment by jpromeror** [comment] 2018-06-14 17:04
Hi @tzuni,

Thanks for reporting this bug!

I will try to correct the problem as soon as possible.

Best regards,

- Juan Pablo

**Comment by jpromeror** [comment] 2018-10-16 11:52
The problem is identified and will be resolved in the following commits!

Thanks!

**Closed by jpromeror** 2018-10-16 11:52 UTC
